### PR TITLE
add buttondown logo

### PR DESCRIPTION
**Pull request by nicolaiarocci**
**What does this PR change? What problem does it solve?**

Add buttondown (https://buttondown.email) icon. 

image
image

## PR Checklist

- [x] I have verified that the code works as described/as intended.
- [x] This change adds a Social Icon which has a permissive license to use it.

### CODE REVIEW

**Comment by zacharyc** [comment]
Should you add this to the documentation as well?

**Comment by nicolaiarocci** [comment]
@zacharyc you mean the wiki? To my knowledge GitHub doesn't support pull requests to the wiki repo. I already cloned and updated it locally, but I see no way to contribute it back.

**Comment by zacharyc** [comment]
@nicolaiarocci you are right, tried the same thing, sorry.

**Review by adityatelange — CHANGES_REQUESTED** [review]
They have svg icon on register page, please pull that 
image

**Comment by nicolaiarocci** [comment]
@adityatelange I can do that. However, a few weeks ago I got in touch with the buttondown service author over email asking for permission, and he said that in his opinion the original logo appears too "bold" compared to the others:

image

He kindly offered to make a custom one for PaperMod, and his custom svg is the one submitted with this PR. If you still want to original, I will update the pull request of course.

**Comment by adityatelange** [comment]
> @adityatelange I can do that. However, a few weeks ago I got in touch with the buttondown service author over email asking for permission, and he said that in his opinion the original logo appears too "bold" compared to the others:
> 
> image image
> He kindly offered to make a custom one for PaperMod, and his custom svg is the one submitted with this PR. If you still want to original, I will update the pull request of course.

I appreciate his efforts to make a custom one for PaperMod. If the owner prefers it this way sure, I will merge it.

**Review by adityatelange — APPROVED** [review]

**Pull request merged**
