### PR TITLE
update Canonical For External Url

### PR DESCRIPTION
**Pull request by Horsty80**
Add custom front matter variable called canonicalUrl
That allow the user add external canonical url.
For example user that write article for his job or on other blogin platform but he want to add the article on his own website

### CODE REVIEW

**Comment by adityatelange** [comment]
We have extended **head support** anything can be added to `<head></head>`

https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-how-to/#custom-head--footer

For your specific used case :-

https://github.com/adityatelange/hugo-PaperMod/blob/f2253b2e836d1404ade0ecd7a325c419ad611cc6/layouts/partials/extend_head.html#L1-L5

**Comment by Horsty80** [comment]
Oh yes ! I haven't read this part of your doc
Thanks ;)

**Comment by Horsty80** [comment]
hum @adityatelange i'm thinking i had my custom code for external canonical url, that not working
because the html will have 2 link canonical : 
 - first the link in `head.html` ->  `<link rel="canonical" href="{{ .Permalink }}" />`
 - second the custom link i will added in `extend_head.html`-> <link rel="canonical" href="{{ .Params.canonicalUrl }}">

I presume that to have 2 canonical url isn't a good idea ^^

**Comment by adityatelange** [comment]
@Horsty80 It's fine to have multiple canonical urls. Canonical urls just let search engines know that their contents are same. You may read about those on the web, for more info :)

**Pull request closed without merging**
