### PR TITLE
Code block / blockquote should respect the margin layout

### LINKED ISSUE #153: Code block / blockquote should respect the margin layout
Code block has a negative margin, so in mobiles, the block looks not aligned.

In the image below, the margin of a normal text and a block can be seen

image

I will provide a PR for it

### PR DESCRIPTION
**Pull request by tomasalmeida**
Should fix #153

### CODE REVIEW

**Comment by adityatelange** [comment]
It is this way by choice and is not a mistake .

**Comment by tomasalmeida** [comment]
Hi @adityatelange, I see your point. My fear is in mobile there is no margin. As the example below:

IMG_20201226_154258

If you prefer to keep it as is now. Please close this PR. I changed the css on my side using extended css.

Thank you for your effort creating the template

**Comment by adityatelange** [comment]
@tomasalmeida Can you enable maintainer edits, as I have to add few more lines to merge the change :)

**Comment by tomasalmeida** [comment]
Hi @adityatelange, it is enabled! Thank you!!

**Comment by tomasalmeida** [comment]
Thanks for merging it! Are you creating a release soon? Or should I use `master` branch?

**Comment by adityatelange** [comment]
@tomasalmeida release will be created after fixing present issues most probably, and after release we'll be switching over from hljs  to hugo's chroma highlighter by default ; ) You may use master branch

**Comment by tomasalmeida** [comment]
👏 👏 👏 👏  I will review the bugs to try to help if I can! 

Thanks for your great work!

**Pull request merged**
