### PR TITLE
Add social icon for unsplash

### PR DESCRIPTION
**Pull request by Explore-Space**
Add social icon for [Unsplash](https://unsplash.com/).

>Unsplash is a website dedicated to sharing stock photography under the Unsplash license.

### CODE REVIEW

**Comment by adityatelange** [comment]
@Explore-Space I see unsplash brand icon is diff  than what it is in this PR

image


https://unsplash.com/press

**Comment by Explore-Space** [comment]
> @Explore-Space I see unsplash brand icon is diff than what it is in this PR
> 
> image
> 
> https://unsplash.com/press

Hi,
I also noticed this problem. But I think the camera icon is more in line with the style of other social icons. If the official logo is used, it looks a little inappropriate.

- Code using official icons
```html
{{- else if (eq $icon_name "unsplash") -}}
<svg viewBox="0 0 32 32" width="32" height="32" xmlns="http://www.w3.org/2000/svg">
    <path d="M10 9V0h12v9H10zm12 5h10v18H0V14h10v9h12v-9z" fill="currentColor" fill-rule="nonzero" />
</svg>
```

- The effect of using the above code
light_mode
dark_mode

Which style do you think is more appropriate?😂

**Comment by adityatelange** [comment]
> > @Explore-Space I see unsplash brand icon is diff than what it is in this PR
> > image
> > https://unsplash.com/press
> 
> Hi,
> I also noticed this problem. But I think the camera icon is more in line with the style of other social icons. If the official logo is used, it looks a little inappropriate.
> 
> * Code using official icons
> 
> ```
> {{- else if (eq $icon_name "unsplash") -}}
> <svg viewBox="0 0 32 32" width="32" height="32" xmlns="http://www.w3.org/2000/svg">
>     <path d="M10 9V0h12v9H10zm12 5h10v18H0V14h10v9h12v-9z" fill="currentColor" fill-rule="nonzero" />
> </svg>
> ```
> 
> * The effect of using the above code
>   light_mode
>   dark_mode
> 
> Which style do you think is more appropriate?

I don't mind if you don't have any problem.

**Comment by adityatelange** [comment]
@Explore-Space I was positive with the camera logo ! Didn't get why did you changed it ?

**Comment by Explore-Space** [comment]
> @ Explore-Space我对相机徽标很满意！没明白为什么要更改它吗？

Oh, I'm very sorry, I just lost my mind. Wait a moment, I change it back.

**Comment by adityatelange** [comment]
> > @ Explore-Space我对相机徽标很满意！没明白为什么要更改它吗？
> 
> Oh, I'm very sorry, I just lost my mind. Wait a moment, I change it back.

If you could enabled maintainer edits it I'd do that for you

**Comment by Explore-Space** [comment]
> > > @探索空间我对相机徽标很满意！没明白为什么要更改它吗？
> > 
> > 
> > 哦，我很抱歉，我只是失去了我的脑海里。请稍等，我将其改回。
> 
> 如果您可以启用维护者编辑功能，我会为您完成

Okay, then you can help me change it back. Sorry for the trouble.

**Review by adityatelange — APPROVED** [review]

**Pull request merged**
