### PR TITLE
.yml --> .toml

### PR DESCRIPTION
**Pull request by Arpitgoyalgg**

### CODE REVIEW

**Comment by fkohrt** [comment]
While you can store the configuration in [TOML](https://github.com/toml-lang/toml) format in a file `config.toml`, PaperMod uses the [YAML](https://yaml.org/) format [throughout the documentation](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#intro). And the following theme setting is YAML syntax:

```yml
theme: "PaperMod"
```

In TOML you'd have to write

```toml
theme = "PaperMod"
```

[Hugo doesn't care which format you use.](https://gohugo.io/getting-started/configuration/)

**Comment by Arpitgoyalgg** [comment]
> While you can store the configuration in [TOML](https://github.com/toml-lang/toml) format in a file `config.toml`, PaperMod uses the [YAML](https://yaml.org/) format [throughout the documentation](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#intro). And the following theme setting is YAML syntax:
> 
> ```yaml
> theme: "PaperMod"
> ```
> 
> In TOML you'd have to write
> 
> ```toml
> theme = "PaperMod"
> ```
> 
> [Hugo doesn't care which format you use.](https://gohugo.io/getting-started/configuration/)

I just changed it because I found ```toml``` instead of ```yml```. No one should be misled in any way, right? Please suggest changes if you can.

**Comment by kdkasad** [comment]
> > While you can store the configuration in [TOML](https://github.com/toml-lang/toml) format in a file `config.toml`, PaperMod uses the [YAML](https://yaml.org/) format [throughout the documentation](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#intro). And the following theme setting is YAML syntax:
> > ```yaml
> > theme: "PaperMod"
> > ```
> > 
> > 
> > In TOML you'd have to write
> > ```toml
> > theme = "PaperMod"
> > ```
> > 
> > 
> > [Hugo doesn't care which format you use.](https://gohugo.io/getting-started/configuration/)
> 
> I just changed it because I found `toml` instead of `yml`. No one should be misled in any way, right? Please suggest changes if you can.

Not sure I'm understanding you. The example site uses YAML, not TOML. So all the examples should be added to `config.yml`, *not* `config.toml`.

**Comment by adityatelange** [comment]
While you can store the configuration in [TOML](https://github.com/toml-lang/toml) format in a file `config.toml`, PaperMod uses the [YAML](https://yaml.org/) format [throughout the documentation](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#intro). And the following theme setting is YAML syntax:

```yml
theme: "PaperMod"
```

In TOML you'd have to write

```toml
theme = "PaperMod"
```

[Hugo doesn't care which format you use.](https://gohugo.io/getting-started/configuration/)

_Originally posted by @fkohrt in https://github.com/adityatelange/hugo-PaperMod/issues/209#issuecomment-769265583_

**Pull request closed without merging**
