### PR TITLE
social-icons: add svg for Mastodon

### PR DESCRIPTION
**Pull request by gikari**
from: https://joinmastodon.org/press-kit.zip

close adityatelange#81

Previews:

image
image

### CODE REVIEW

**Comment by adityatelange** [comment]
@gikari Why not use https://joinmastodon.org/static/media/logo_transparent_white.6a441138.svg
simpler path right ?

Also can you arrange it alphabetically according to its name ?

**Comment by gikari** [comment]
> Why not use https://joinmastodon.org/static/media/logo_transparent_white.6a441138.svg
> simpler path right ?
I thought it would not fit, since it's not wire-styled, but since you do not mind, I will change it to that.

**Comment by adityatelange** [comment]
> > Why not use https://joinmastodon.org/static/media/logo_transparent_white.6a441138.svg
> > simpler path right ?
> 
> I thought it would not fit, since it's not wire-styled, but since you do not mind, I will change it to that.

Nope its Fine ! :+1:

**Comment by adityatelange** [comment]
@gikari Thank you for contributing :)

**Comment by gikari** [comment]
> @gikari Thank you for contributing :)

You're welcome :)

**Comment by adityatelange** [comment]
@gikari It would be great if you could add icon to https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/content/posts/papermod/papermod-icons.md

**Pull request merged**
