### PR TITLE
Fix breadcrumbs displaying problem

### PR DESCRIPTION
**Pull request by simba-fs**
**What does this PR change? What problem does it solve?**
To fix breadcrumbs displaying problem

old one -> 
Screenshot 2021-12-25 at 11-52-45 LaTeX Starter

new one -> 
Screenshot 2021-12-25 at 11-52-02 LaTeX Starter

**Was the change discussed in an issue or in the Discussions before?**
No, I didn't find something related

## PR Checklist

- [ ] This change adds/updates translations and I have used the [template present here](https://github.com/adityatelange/hugo-PaperMod/wiki/Translations#want-to-add-your-language-).
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have verified that the code works as described/as intended.
- [ ] This change adds a Social Icon which has a permissive license to use it.
- [x] This change **does not** include any CDN resources/links.
- [x] This change **does not** include any unrelated scripts such as bash and python scripts.
- [ ] This change updates the overridden internal templates from HUGO's repository.

### CODE REVIEW

**Comment by adityatelange** [comment]
Hi @simba-fs 

Can you share a sample site config where this problem arises?

I see the breadcrumbs are generating perfectly fine with demo here
https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/

with 
https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/content/posts/papermod/papermod-installation.md 
as source

**Comment by simba-fs** [comment]
@adityatelange   

I use branch bundle to manage my posts, maybe it's the cause of the bug.

my website: https://blog.simba-fs.dev/posts/other/latex-starter/  
source: https://github.com/simba-fs/simba-fs.github.io/blob/master/content/posts/other/latex-starter.md
config: https://github.com/simba-fs/simba-fs.github.io/blob/master/config.toml

**Comment by adityatelange** [comment]
@simba-fs This can still be reproduced?

**Comment by simba-fs** [comment]
@adityatelange It is already fixed, thanks

**Comment by adityatelange** [comment]
> @adityatelange It is already fixed, thanks

Great! closing :+1:

**Pull request closed without merging**
