### PR TITLE
add kakaotalk svm image

### PR DESCRIPTION
**Pull request by pacientes**
add social icon **KakaoTalk**

kakaotalk

KakaoTalk is a popular sns service in Korea.
Group chat between users through the 'open chat'.
And also it's a service similar to Slack.

### CODE REVIEW

**Comment by pacientes** [comment]
commit message error..;;
svm -> svg

**Comment by adityatelange** [comment]
@pacientes That icon doesn't look well aligned, its been cut from all 4 sides, moreover the TALK words are sticking to each other

**Comment by pacientes** [comment]
thanks for feedback.

how about this image?
kakaotalk2

**Comment by adityatelange** [comment]
@pacientes looks fine to me,
also don't forget to add it alphabetically just like other svgs are !

**Comment by pacientes** [comment]
@adityatelange 
wow! I'm really happy that it looks okay.
I will close this pull request and update what you said and upload it.

**Comment by adityatelange** [comment]
@pacientes you may add those commits directly to this branch No need of new PR !

**Comment by adityatelange** [comment]
@pacientes are you using https://www.flaticon.com/svg/static/icons/svg/2111/2111683.svg ?

**Comment by pacientes** [comment]
@adityatelange yes. i'm using https://www.flaticon.com/svg/static/icons/svg/2111/2111683.svg

**Pull request closed without merging**
