### PR TITLE
Rgba to rgb

### PR DESCRIPTION
**Pull request by adityatelange**
**What does this PR change? What problem does it solve?**

Because the theme's colors are set using opacity instead of actual color values, they interfere with elements other than text. For example, dark elements styled by entry-content use the --secondary color of rgba(255, 255, 255, 0.56). The text reads fine as a grey color against the black background, but if you add an emoji into your content it will also take on the 0.56 opacity value and look like it's fading away.

This PR includes: Same color, but no opacity issues.

The opacity of `go to top` button also changes here

**Was the change discussed in an issue or in the Discussions before?**

[BUG] Emojis affected by theme opacity values Fixes: #557

## PR Checklist

- [ ] This change adds/updates translations and I have used the [template present here](https://github.com/adityatelange/hugo-PaperMod/wiki/Translations#want-to-add-your-language-).
- [ ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have verified that the code works as described/as intended.
- [ ] This change adds a Social Icon which has a permissive license to use it.
- [ ] This change **does not** include any CDN resources/links.
- [ ] This change **does not** include any unrelated scripts such as bash and python scripts.
- [ ] This change updates the overridden internal templates from HUGO's repository.

### CODE REVIEW

**Comment by adityatelange** [comment]
@aormsby @kdkasad Please check whether the colors look the same of different. Also let me know if there are any other visual differences

**Comment by aormsby** [comment]
@adityatelange Looks pretty solid to me 👍

**Review by kdkasad — APPROVED** [review]
LGTM!

**Comment by aormsby** [comment]
Just bumping this. I'd happily help deal with the conflicts, but I don't have write permission. 😅

**Pull request merged**
