### PR TITLE
Add raycast logo

### PR DESCRIPTION
**Pull request by nagauta**
**What does this PR change? What problem does it solve?**
there is no icon support for [raycast](https://www.raycast.com/) so i wanna add the icon.
I use the icon from [brand guideline](https://www.raycast.com/templates/brand-guidelines)
スクリーンショット 2024-02-24 15 18 04

**Was the change discussed in an issue or in the Discussions before?**
I have not discussed.

## PR Checklist

- [ ] This change adds/updates translations and I have used the [template present here](https://github.com/adityatelange/hugo-PaperMod/wiki/Translations#want-to-add-your-language-).
- [ ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have verified that the code works as described/as intended.
- [x] This change adds a Social Icon which has a permissive license to use it.
- [x] This change **does not** include any CDN resources/links.
- [x] This change **does not** include any unrelated scripts such as bash and python scripts.
- [ ] This change updates the overridden internal templates from HUGO's repository.

### CODE REVIEW

**Comment by nagauta** [comment]
@adityatelange 
Hi, thanks for creating cool theme.

I'd love to add icon of rayacst.
should I modify this icon to fit theme right?

**Comment by adityatelange** [comment]
> I'd love to add icon of rayacst. should I modify this icon to fit theme right?

Yes please

**Comment by nagauta** [comment]
I'm working on it!
Yes, raycast have a user profile page like below.
https://www.raycast.com/nagauta

**Comment by nagauta** [comment]
I modified logo to fit theme, please review this

## light mode
スクリーンショット 2024-03-03 20 25 24

##. dark mode
スクリーンショット 2024-03-03 20 26 15

**Review by adityatelange — APPROVED** [review]
LGTM :+1:

**Pull request merged**
