### PR TITLE
Add i18n support for Arabic

### PR DESCRIPTION
**Pull request by Muhammad-Saad-01**

### CODE REVIEW

**Review by adityatelange — CHANGES_REQUESTED** [review]
One more translated string is remaining `home`

read this https://github.com/adityatelange/hugo-PaperMod/wiki/Translations#want-to-add-your-language-

**Comment by Muhammad-Saad-01** [comment]
ar.yaml updated with remaining changes.

**Comment by adityatelange** [comment]
> ar.yaml updated with remaining changes.

I am getting these warns while building, but couldn't  figure out why. Do you get these ?

```
WARN 2021/02/28 12:27:57 Failed to get translated string for language "ar" and ID "read_time": message "read_time" has no plural form "few"
WARN 2021/02/28 12:27:57 Failed to get translated string for language "ar" and ID "read_time": message "read_time" has no plural form "few"
WARN 2021/02/28 12:27:59 Failed to get translated string for language "ar" and ID "read_time": message "read_time" has no plural form "two"
WARN 2021/02/28 12:27:59 Failed to get translated string for language "ar" and ID "read_time": message "read_time" has no plural form "zero"
```

**Comment by Muhammad-Saad-01** [comment]
I didn't build it, just created the file.  it just because of plural forms of counting numbers in Arabic, check it again.

**Comment by adityatelange** [comment]
> I didn't build it, just created the file. it just because of plural forms of counting numbers in Arabic, check it again.

We also have Farsi in `i18n` list but these warings were't there, what's the catch here ?

https://github.com/adityatelange/hugo-PaperMod/blob/3492e151e5a53c53f23487fea93d44f7f97670b0/i18n/fa.yaml#L1-L16

**Review by adityatelange — APPROVED** [review]

**Comment by Muhammad-Saad-01** [comment]
that's interesting, I don't know if Farsi has different plural forms or not but I will check it out :).

**Pull request merged**
