### PR TITLE
Make "Powered by" translatable

### PR DESCRIPTION
**Pull request by fkohrt**

### CODE REVIEW

**Comment by adityatelange** [comment]
Is this really needed ? IMO not.
Likewise we need to translate a ton of stuff, including dates and "Theme" string.

**Comment by fkohrt** [comment]
What triggered this for me was that a localized `copyright` string clashed with the non-localized _Powered by_ in the footer. I thought about _Theme_, but that can be regarded as a fixed Hugo term. And localization of dates can already be achieved with

```yml
languages:
  en:
    languageName: English
    params:
      DateFormat: 'January 2, 2006'
```

Or what other localization did you have in mind?

**Comment by adityatelange** [comment]
> What triggered this for me was that a localized `copyright` string clashed with the non-localized _Powered by_ in the footer and provides a bad experience with screen readers. I thought about _Theme_, but that could be regarded as a fixed Hugo term.

I agree

**Comment by fkohrt** [comment]
@adityatelange Alright, I have accounted for that.

> Likewise we need to translate a ton of stuff

What probably still lacks translation are the accessible names such as `aria-label`. But that's for another PR...

**Comment by RealA10N** [comment]
> Is this really needed ? IMO not.
> Likewise we need to translate a ton of stuff, including dates and "Theme" string.

I think that yes, it should indeed be translated. If someone is building a website in a language other than English, those little "patches" of English can be really annoying. In any case, strings *should not* be hardcoded.

**Pull request closed without merging**
