### PR TITLE
Minor adjustments in Arabic translations

### PR DESCRIPTION
**Pull request by bassel**

### CODE REVIEW

**Comment by adityatelange** [comment]
I don't mind but if you (@bassel ) and @Muhammad-Saad-01 (#271) could discuss it about right or wrong it, it would be nicer ..

**Comment by bassel** [comment]
Both version are valid in terms of meaning, it's just that this one is kind of more grammatically correct since it uses the dictionary versions of the words. What do you think @Muhammad-Saad-01 ?

**Comment by mohnoor94** [comment]
+1 for this.

**Comment by adityatelange** [comment]
Merging

**Pull request merged**
