### PR TITLE
Add post description

### PR DESCRIPTION
**Pull request by weicliu**
Usage example already exists in the markdown-syntax.md: https://github.com/adityatelange/hugo-PaperMod/blame/exampleSite/content/posts/markdown-syntax.md#L5

### CODE REVIEW

**Review by adityatelange — APPROVED** [review]

**Comment by mukhtharcm** [comment]
But where does the description is shown?

**Comment by kdkasad** [comment]
> But where does the description is shown?

Between the post title and the cover image:
screenshot

**Comment by mukhtharcm** [comment]
Oh!,
Is there any way to show it on the post list page,?
Instead of showing  the starting lines of the post, it'd been cool if we can show a description instead

**Comment by kdkasad** [comment]
> Oh!,
> Is there any way to show it on the post list page,?
> Instead of showing the starting lines of the post, it'd been cool if we can show a description instead

Currently, I don't think so, but it wouldn't be hard to implement. Try giving it a shot. Take a look at the changes made in this PR and try to do the same in `layouts/_default/list.html`.

**Comment by mukhtharcm** [comment]
Thanks. 
I'll try it in the morning. 
It's 1.30 at night here 😀😀

**Pull request merged**
