### PR TITLE
Prev next post links on single post page

### PR DESCRIPTION
**Pull request by adityatelange**
- In Site config: `Params.ShowPostNavLinks: true`

### CODE REVIEW

**Comment by adityatelange** [comment]
## Demo

<kbd>image
</kbd>

<kbd>image</kbd>

**Comment by kdkasad** [comment]
Looks great!

**Comment by adityatelange** [comment]
> Looks great!

I still feel the position isn't great, and I am not having any other ideas to fix this.

**Comment by kdkasad** [comment]
> > Looks great!
> 
> I still feel the position isn't great, and I am not having any other ideas to fix this.

I wonder if for the mobile layout, it might be better to omit the titles of the next/previous posts and instead use a button like the **Next Page** button from the homepage.

**Comment by adityatelange** [comment]
> > > Looks great!
> > 
> > 
> > I still feel the position isn't great, and I am not having any other ideas to fix this.
> 
> I wonder if for the mobile layout, it might be better to omit the titles of the next/previous posts and instead use a button like the **Next Page** button from the homepage. That way they'd fit side-by-side.

Yes you are correct, I have tried it but it doesn't look good at all with long text titles and also with emoji's.
(On the Home Page the buttons aren't user editable, making it smaller)

**Comment by muhammadhanif** [comment]
> ## Demo
> image
> 
> image

In my opinion, the prev-next post links would be nice if it is placed below of share buttons . Why? Because the share buttons is still part of the post (for sharing the post).

This is what I implement on my site.

screenshot-hanifmu com-2021 01 19-15_51_12

**Comment by adityatelange** [comment]
> In my opinion, the prev-next post links would be nice if it is placed below of share buttons . Why? Because the share buttons is still part of the post (for sharing the post).
> 
> This is what I implement on my site.
> 
> screenshot-hanifmu com-2021 01 19-15_51_12
> 

The design does match #183 :)

**Comment by muhammadhanif** [comment]
> > In my opinion, the prev-next post links would be nice if it is placed below of share buttons . Why? Because the share buttons is still part of the post (for sharing the post).
> > This is what I implement on my site.
> > screenshot-hanifmu com-2021 01 19-15_51_12
> 
> The design does match #183 :)

absolutely yes 😁

by the way, Thank you for releasing this great theme 👍

**Comment by kdkasad** [comment]
> In my opinion, the prev-next post links would be nice if it is placed below of share buttons . Why? Because the share buttons is still part of the post (for sharing the post).
> 
> This is what I implement on my site.
> 
> screenshot-hanifmu com-2021 01 19-15_51_12

Now that I've seen both ways, I agree with this layout.

**Pull request merged**
