### PR TITLE
add douban and zhihu icon

### PR DESCRIPTION
**Pull request by alswl**
**What does this PR change? What problem does it solve?**

Add [douban](http://douban.com/) and [zhihu](https://www.zhihu.com/) icon fron http://www.iconfont.cn/ .
These sites are well-known social web sites in China.

douban is 豆
zhihu is 知

image

**Was the change discussed in an issue or in the Discussions before?**

No icon for douban and zhihu.

## PR Checklist

- [x] This change adds/updates translations and I have used the [template present here](https://github.com/adityatelange/hugo-PaperMod/wiki/Translations#want-to-add-your-language-).
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have verified that the code works as described/as intended.
- [x] This change adds a Social Icon which has a permissive license to use it.
- [x] This change **does not** include any CDN resources/links.
- [x] This change **does not** include any unrelated scripts such as bash and python scripts.
- [x] This change updates the overridden internal templates from HUGO's repository.

### CODE REVIEW

**Comment by alswl** [comment]
@adityatelange Friendly ping.

**Comment by jinmiaoluo** [comment]
Douban: https://www.douban.com/ is similar to Goodreads
Zhihu: https://zhihu.com is similar to Quora

Both are very common social networks in China. 
Hope this PR can be merged.

**Comment by jinmiaoluo** [comment]
@alswl Your commit message have typo, douban, not douabn.

**Review by adityatelange — CHANGES_REQUESTED** [review]
Please add the svgs in alphabetical order by their **name**

**Review by adityatelange — APPROVED** [review]

**Comment by alswl** [comment]
> Please add the svgs in alphabetical order by their **name**

It was fixed, thanks for your response.

**Pull request merged**
