### PR TITLE
feat: add logo to home info page

### PR DESCRIPTION
**Pull request by leovct**
## Description

- Add logo to home info page
- Standardise the home info parameters (e.g. use `.title` instead of `.Title`)

The configuration looks like the following:

```yaml
params:
  homeInfoParams:
    title: Bonjour! 👋
    image:
      url: my-image.png
      title: My Title
      link : mylink.com
```

If the image url is not specified, no image is shown and if the image link is not specified, there's not link on top of the image.

## Issue

Related to #216

## Preview

Screenshot 2023-05-10 at 02 45 19

See https://leovct.github.io/

## PR Checklist

- [ ] This change adds/updates translations and I have used the [template present here](https://github.com/adityatelange/hugo-PaperMod/wiki/Translations#want-to-add-your-language-).
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have verified that the code works as described/as intended.
- [ ] This change adds a Social Icon which has a permissive license to use it.
- [x] This change **does not** include any CDN resources/links.
- [x] This change **does not** include any unrelated scripts such as bash and python scripts.
- [ ] This change updates the overridden internal templates from HUGO's repository.

### CODE REVIEW

**Comment by leovct** [comment]
I recognise that it takes a lot of time and energy to maintain an open-source repository, @adityatelange would you like to delegate some of the work to contributors? We could organise a call to coordinate on the direction to take and the best practices to follow! :)

**Comment by leovct** [comment]
> I am also highly interested by having an optional profile picture in Home Info mode.

It looks like the maintainer is not active... If you want to use this feature, I recommend you to fork this repo, merge the changes from this branch to your main branch and make your hugo website point to your fork.

**Comment by gschurck** [comment]
Yep, that's exactly what I did. I changed a few things to make it look better for me, especially on mobile : 
- https://gschurck.github.io/
- https://github.com/gschurck/hugo-papermod

**Comment by svsk1ng** [comment]
@leovct  Can you please help me put a logo at my home-info page?
I followed ur instructions but still, i cannot see the logo.

**Comment by leovct** [comment]
> @leovct Can you please help me put a logo at my home-info page? I followed ur instructions and locally its perfect (localhost). My problem is that i am using my image URL (https://........) and it is not working. I deployed hugo on cloudflare. any idea how i can fix it? heres a partial example of my config file: homeInfoParams: title: Hey! image: url: https://www.i.imgur.com/d0pdui4.png

Interesting... I just tried with an img from the web and it looks like it works locally and when I deploy it to github for me. Maybe check your Cloudflare configuration?

**Comment by svsk1ng** [comment]
Silly me... the problem was that i tried to change assets and layouts in theme directory but i followed ur repo and now its okay... sorry its my first time coding... Thanks again for the help :)

**Pull request closed without merging**
