### PR TITLE
Add new icon to icon list

### PR DESCRIPTION
**Pull request by daksh7011**
Add snapchat icon entry in table and updated indices of the subsequent entries.

### CODE REVIEW

**Comment by daksh7011** [comment]
@adityatelange Please review and merge the branch to update changes.

**Comment by adityatelange** [comment]
> @adityatelange Please review and merge the branch to update changes.

It is unnecessary to tag me. I'll still read your PR

**Comment by daksh7011** [comment]
Well, I forgot its public repo. We keep notifications off unless we get mention in many of our repos. So I am used to that regime. I'll be aware next time XD

**Review by adityatelange — APPROVED** [review]
Thanks

**Pull request merged**
