### PR TITLE
Add social icon for snapchat

### PR DESCRIPTION
**Pull request by daksh7011**
Add social icon for Snapchat.

The SVG is taken from Snapchat official assets, So please try not to modify it.

### CODE REVIEW

**Comment by daksh7011** [comment]
This PR will close #186 when merged.

**Comment by daksh7011** [comment]
@adityatelange Please review and merge the PR at your convenience.

**Review by adityatelange — CHANGES_REQUESTED** [review]
Doesn't match style SVGs already present. 
Won't look good with dark and light more.

**Comment by daksh7011** [comment]
Light Mode preview
image

Dark Mode preview:
image

It does look good, Changing the SVG would break [Snapchat's ToS](https://support.snapchat.com/en-US/a/ghost-logo-usage) which states: "Don’t alter, rotate, or modify the Ghost logo in any way, such as by changing colors or adding"

**Comment by adityatelange** [comment]
@daksh7011 Why not use icon from [simpleicons.org](https://simpleicons.org) and modify accordingly ? Better licensing, smaller size.

**Comment by daksh7011** [comment]
@adityatelange I have changed the svg from official one to SimpleIcons.org.

Have a look at your convenience.

**Review by adityatelange — APPROVED** [review]
Looks good. Although it is not of wire type, it's fine IMO.
Merging, Thanks !

**Comment by adityatelange** [comment]
@daksh7011 It would be great if you could also add the icon to icon list :)
https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/content/posts/papermod/papermod-icons.md

**Comment by daksh7011** [comment]
@adityatelange I can add a alternate logo with just strokes as `snapchat-alt`. Let me know, I will add it.

**Pull request merged**
