### PR TITLE
Update translation of zh-tw

### PR DESCRIPTION
**Pull request by DejavuMoe**
**What does this PR change? What problem does it solve?**

Update the translation of `Prev Page` and `Next Page` in Traditional Chinese

**Was the change discussed in an issue or in the Discussions before?**

## PR Checklist

- [x] This change adds/updates translations and I have used the [template present here](https://github.com/adityatelange/hugo-PaperMod/wiki/Translations#want-to-add-your-language-).
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have verified that the code works as described/as intended.
- [ ] This change adds a Social Icon which has a permissive license to use it.
- [x] This change **does not** include any CDN resources/links.
- [x] This change **does not** include any unrelated scripts such as bash and python scripts.
- [ ] This change updates the overridden internal templates from HUGO's repository.

### CODE REVIEW

**Comment by adityatelange** [comment]
@ChiahongHong @yuyinws @DotnetChen Pls approve

**Review by yuyinws — APPROVED** [review]

**Comment by yuyinws** [comment]
@adityatelange I had review this PR, It's correct and can be merged.

**Comment by adityatelange** [comment]
@DejavuMoe can we include #914 as well with this

**Comment by DejavuMoe** [comment]
> @DejavuMoe can we include #914 as well with this

I think #914 should not have much effect on Chinese translation.

In Chinese (either Simplified or Traditional Chinese), the previous or next button on a page and post should be different terms, and I think they should be translated separately, for example

**For pages**

- `Previous` and `Next`
- `上一页` 和 `下一页`

**For article**

- `Previous` or `Next`
- `上一篇` 和 `下一篇`

image
image

🧐Any suggestions? Please~

@ChiahongHong @yuyinws @DotnetChen

**Comment by yuyinws** [comment]
@DejavuMoe @adityatelange 
I think the better way is add two new keywords in i18n file to distinguish `Page` and `Post`. like this:

```yaml
# en.yaml
- id: prev_page
  translation: "Prev"

- id: next_page
  translation: "Next"

- id: prev_post
  translation: "Prev"

- id: next_post
  translation: "Next"
```

In Chinese, It will be translated like this:
```yaml
- id: prev_page
  translation: "上一页"

- id: next_page
  translation: "下一页"

- id: prev_post
  translation: "上一篇"

- id: next_post
  translation: "下一篇"
```

**Comment by DejavuMoe** [comment]
> @DejavuMoe @adityatelange I think the better way is add two new keywords in i18n file to distinguish `Page` and `Post`. like this:
> 
> ```yaml
> # en.yaml
> - id: prev_page
>   translation: "Prev"
> 
> - id: next_page
>   translation: "Next"
> 
> - id: prev_post
>   translation: "Prev"
> 
> - id: next_post
>   translation: "Next"
> ```
> 
> In Chinese, It will be translated like this:
> 
> ```yaml
> - id: prev_page
>   translation: "上一页"
> 
> - id: next_page
>   translation: "下一页"
> 
> - id: prev_post
>   translation: "上一篇"
> 
> - id: next_post
>   translation: "下一篇"
> ```

@adityatelange @yuyinws 
 Yes, I think it's a good way, totally agree with the way #892 updated the translation.

**Comment by adityatelange** [comment]
How about we just have translations for 'next and previous' instead of 'next_page/next_post'? I hope that is doable.
The more translations more PRs harder will it be to maintain.
Although it already was next_page and never next_post, I think it will be fine if ee keep it as it is, if that's not a problem.

**Comment by DejavuMoe** [comment]
> How about we just have translations for 'next and previous' instead of 'next_page/next_post'? I hope that is doable. The more translations more PRs harder will it be to maintain. Although it already was next_page and never next_post, I think it will be fine if ee keep it as it is, if that's not a problem.

Mmmm, in Chinese, a separate `next and previous` should be a bit strange. But using `next_page/next_post` would indeed make the current i18n project more difficult (until all languages get updated contributions in time, otherwise it might break the current translations for some languages)

And the semantics of `next_page` should be stronger than `next_post` in Chinese, so I only updated the translation of `previous_page ` - `next_page` in my PR, which is acceptable.

**Review by adityatelange — APPROVED** [review]

**Pull request merged**
