### PR TITLE
Add svg for X

### PR DESCRIPTION
**Pull request by zanseb**
Add svg for `X` https://x.com formerly known as twitter.

image
image

### CODE REVIEW

**Comment by Mombuyish** [comment]
Good work! but you are missing share button and settings in config file, can you fix it?

**Comment by zanseb** [comment]
image
image

**Comment by zanseb** [comment]
What should I add to the config file?

**Comment by Mombuyish** [comment]
> What should I add to the config file?

Sorry I mean you should update the sample site and wiki config.

https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml
https://github.com/adityatelange/hugo-PaperMod/wiki

it's really helpful that this PR. Thank you.

**Comment by zanseb** [comment]
Oh ok. I can provide you a patch for the wiki: [0001-Document-X-social-icon.patch](https://github.com/adityatelange/hugo-PaperMod/files/12236308/0001-Document-X-social-icon.patch)

I'll create a separate PR for the demo site.

**Comment by zanseb** [comment]
Ok done. I hope I did everything correctly 🙂

**Comment by adityatelange** [comment]
we'll wait until x.com is live

**Comment by nielsbrakel** [comment]
@adityatelange Can this be merged?

**Review by adityatelange — APPROVED** [review]

**Pull request merged**
