### PR TITLE
Specify input type of search field

### PR DESCRIPTION
**Pull request by fkohrt**
Recommendation as per https://ffoodd.github.io/a11y.css/errors.html#no-type
See also https://references.modernisation.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-11-11

### CODE REVIEW

**Comment by adityatelange** [comment]
> Recommendation as per https://ffoodd.github.io/a11y.css/errors.html#no-type
> See also https://references.modernisation.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-11-11

1. I don't understand French.
2. It is same as text and search, as there is no Form being submitted rn.
3. This change adds a cross sign in the end for which a on click handler needs to be added.

**Comment by fkohrt** [comment]
1. Nevermind, I provided the second (french) link only because those RGAA guidelines are cited in the first link but with a broken link.
2. I'm not sure about the importance of this commit accessibility wise, but it has been a suggestion of the [a11y.css](https://ffoodd.github.io/a11y.css/) tool so I thought I'd share.
3. I believe this is browser specific behaviour (Firefox doesn't show this), so not sure why and how a onclick handler should be added.

So feel free to use to close this if you don't consider it worth – not sure about this either.

**Comment by fkohrt** [comment]
@adityatelange I don't see anything to improve this commit right now, or would you rather see the cross sign hidden?

**Comment by adityatelange** [comment]
Sorry but I don't think we need this

**Pull request closed without merging**
